### ISSUE TITLE
Implement cloud-init data templating for getting node advertise address

### ISSUE THREAD

**Issue by Tomy2e** [scaleway/cluster-api-provider-scaleway#6]
When an instance has both a Public IP and VPC IP, we may want the control-plane components to use the VPC IP as their advertise address.

The instance metadata does not contain the VPC IP (it only has the `ipam_ip_ids`). The provider should provide the VPC IP via a templating system so that users can include it in their configurations.

For example:

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: kcp
spec:
  kubeadmConfigSpec:
    initConfiguration:
      localAPIEndpoint:
        advertiseAddress: "[[[ .NodeIP ]]]"
      nodeRegistration:
        kubeletExtraArgs:
          node-ip: "[[[ .NodeIP ]]]"
    joinConfiguration:
      controlPlane:
        localAPIEndpoint:
          advertiseAddress: "[[[ .NodeIP ]]]"
      nodeRegistration:
        kubeletExtraArgs:
          node-ip: "[[[ .NodeIP ]]]"
```
